import { makeStyles, shorthands } from "@fluentui/react-components";

export const AnswerStyles = makeStyles({
    answerContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        ...shorthands.padding('8.1285px'),
        ...shorthands.gap('5.42px'),
        //background: '#FFFFFF',
        boxShadow: '0px 1px 2px rgba(0, 0, 0, 0.14), 0px 0px 2px rgba(0, 0, 0, 0.12)',
        ...shorthands.borderRadius('5.419px'),
    },
    answerText: {
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '14px',
        lineHeight: '20px',
        ...shorthands.flex('none'),
        order: 1,
        alignSelf: 'stretch',
        flexGrow: 0,
        ...shorthands.margin('11px'),
        whiteSpace: 'normal',
        wordWrap: 'break-word',
        maxWidth: '800px',
        overflowX: 'auto',
    },
    answerFooter: {
        display: 'flex',
        // flexFlow: 'row nowrap',
        width: '100%',
        height: 'auto',
        boxSizing: 'border-box',
        justifyContent: 'space-between',
    },
    answerDisclaimerContainer: {
        justifyContent: 'center',
        display: 'flex',
    },
    answerDisclaimer: {
        fontStyle: 'normal',
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '16px',
        display: 'flex',
        alignItems: 'center',
        textAlign: 'center',
        ...shorthands.flex('none'),
        order: 1,
        flexGrow: 0,
    },
    citationContainer: {
        marginLeft: '10px',
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '12px',
        lineHeight: '16px',
        color: '#115EA3',
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'center',
        ...shorthands.padding('4px', '6px'),
        ...shorthands.gap('4px'),
        ...shorthands.border('1px solid #D1D1D1'),
        ...shorthands.borderRadius('4px'),
        '&:hover': {
            ...shorthands.textDecoration('underline'),
            cursor: 'pointer',
        },
    },
    citation: {
        boxSizing: 'border-box',
        display: 'inline-flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        ...shorthands.padding('0px'),
        width: '14px',
        height: '14px',
        ...shorthands.border('1px solid #E0E0E0'),
        ...shorthands.borderRadius('4px'),
        ...shorthands.flex('none'),
        flexGrow: 0,
        zIndex: 2,
        fontStyle: 'normal',
        fontWeight: 600,
        fontSize: '10px',
        lineHeight: '14px',
        textAlign: 'center',
        cursor: 'pointer',
        '&:hover': {
            ...shorthands.textDecoration('underline'),
            cursor: 'pointer',
        },
    },
    accordionIcon: {
        display: 'inline-flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        ...shorthands.padding('0px'),
        marginTop: '4px',
        fontSize: '10px',
        '&:hover': {
            cursor: 'pointer',
        },
    },
    accordionTitle: {
        marginRight: '5px',
        marginLeft: '10px',
        fontStyle: 'normal',
        lineHeight: '16px',
        display: 'flex',
        alignItems: 'center',
        '&:hover': {
            cursor: 'pointer',
        },
    },
});
