# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Build Frontend

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
    

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: frontend
#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x, 21.x]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: '**/package-lock.json'
#     - run: npm ci
#     - run: NODE_OPTIONS=--max_old_space_size=8192 npm run build --if-present
#     - run: npm run test --if-present

name: Build Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm install --save-dev @fluentui/react
        npm install --verbose

    - name: Build project
      run: npm run build --if-present
      env:
        NODE_OPTIONS: --max_old_space_size=8192

    - name: Run tests
      run: npm test --if-present