name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: set_tag
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/intranettchatbot:${{ github.run_id }}
          docker build . --file WebApp.Dockerfile --tag $IMAGE_TAG
          docker push $IMAGE_TAG
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Production
    steps:
      - name: Debug Azure creds
        run: echo "${{ secrets.AZURE_CREDENTIALS }}" | jq .
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: intranettchatbot
          slot-name: Production
          images: ghcr.io/${{ github.repository_owner }}/intranettchatbot:${{ github.run_id }}

      - name: Restart Azure Web App
        run: |
          az webapp restart \
            --name intranettchatbot \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

