name: Docker Image Build

on:
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Build the Docker image
      run:         
        docker build . --file WebApp.Dockerfile --tag sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
      
