name: Deploy Docker Image to Azure Web App

on:
  workflow_run:
    workflows: ["Docker Image Build and Push to GHCR"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: intranettchatbot 
          slot-name: Production
          images: ghcr.io/${{ github.repository_owner.toLower() }}/intranettchatbot:${{ github.run_id }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
