name: Deploy Docker Image to Azure Web App

on:
  workflow_run:
    workflows: ["Docker Image Build"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: intranettchatbot 
          slot-name: Production
          images: ghcr.io/${{ github.repository }}/intranettchatbot:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
